server:
  port: 8081
  servlet:
    context-path: /customerMaster-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    application:
      name: customerMaster-service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

